# Use a slim Python image
FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libgeos-dev \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

# System packages needed for elevation + rasterio
RUN apt-get update && apt-get install -y \
    gdal-bin \
    make \
    curl \
    unzip \
    build-essential

# Create app directory
WORKDIR /app

# Copy requirements and install
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt
